_wandb:
    value:
        cli_version: 0.18.6
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 51
                - 53
                - 55
                - 100
                - 103
                - 106
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 51
                - 53
                - 55
                - 100
                - 103
                - 106
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.9
            "5": 0.18.6
            "6": 4.46.2
            "8":
                - 3
                - 5
            "12": 0.18.6
            "13": windows-amd64
eval_batch_size:
    value: 32
eval_splits:
    value:
        - validation
learning_rate:
    value: 2e-05
model_name_or_path:
    value: distilbert-base-uncased
num_labels:
    value: 2
task_name:
    value: mrpc
train_batch_size:
    value: 32
warmup_steps:
    value: 0
weight_decay:
    value: 0
